version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    registries:
      - github
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 5
    open-pull-requests-limit: 2
    target-branch: master